ALTER TABLE settings ADD COLUMN rag_top_k INTEGER NOT NULL DEFAULT 5;
ALTER TABLE settings ADD COLUMN rag_score_threshold REAL NOT NULL DEFAULT 0.5;

ALTER TABLE settings ADD COLUMN temperature REAL NOT NULL DEFAULT 1.0;
ALTER TABLE settings ADD COLUMN top_p REAL NOT NULL DEFAULT 1.0;
ALTER TABLE settings ADD COLUMN top_k INTEGER NOT NULL DEFAULT 0;
ALTER TABLE settings ADD COLUMN frequency_penalty REAL NOT NULL DEFAULT 0.0;
ALTER TABLE settings ADD COLUMN presence_penalty REAL NOT NULL DEFAULT 0.0;
ALTER TABLE settings ADD COLUMN max_response_tokens INTEGER NOT NULL DEFAULT 0;
